version: '3.7'

services:
  reporting:
    build: .
    image: quay.io/ukhomeofficedigital/cop-private-reporting-service
    restart: on-failure
    container_name: reporting
    environment:
      REPORTING_SERVICE_NAME: "reporting"
      SESSION_NAME: dev
      PRIVATE_REDIS_URL: redis
      PRIVATE_REDIS_PORT: 6379
      PRIVATE_REDIS_TOKEN: ""
      SESSION_SECRET: reports
      KEYCLOAK_REALM: dev
      KEYCLOAK_AUTH_URL: "${SCHEME}://keycloak.${DOMAINNAME}/auth"
      KEYCLOAK_CLIENT_ID: reporting
      PROTOCOL: ${PROTOCOL}
      INT_DOMAIN: ${INT_DOMAIN}
      PLATFORM_DATA_NAME: ${PLATFORM_DATA_NAME}
      CORS_ORIGIN: ${CORS_ORIGIN}
    volumes:
      - ${REPORTING_DATA}:/workflow-resources
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:reporting.${DOMAINNAME}"
      - "traefik.port=8080"
      - "traefik.protocol=http"
      - "traefik.docker.network=web"


networks:
  db:
    external:
      name: db
  web:
    external:
      name: web
